version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "32700:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234512345210Ip
      POSTGRES_DB: postgres
  pgAdmin:
    image: dpage/pgadmin4:6.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=1
    volumes:
      - ./docker-data/pgAdmin:/var/lib/pgadmin
    ports:
      - 8080:80
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: